#!/usr/bin/env python3

import argparse
import sys
import requests
from getpass import getpass
import json

parser = argparse.ArgumentParser()
choices = ("playing", "popular", "top", "upcoming")
parser.add_argument("type", choices = choices)
args = parser.parse_args()

match args.type:
    case "playing":
        url_path = "https://api.themoviedb.org/3/movie/now_playing"
    case "popular":
        url_path = "https://api.themoviedb.org/3/movie/popular"
    case "top":
        url_path = "https://api.themoviedb.org/3/movie/top_rated"
    case "upcoming":
        url_path = "https://api.themoviedb.org/3/movie/upcoming"
    case _:
        print("Error, unknown argument for movie type to list.")
        sys.exit()

token = getpass("Enter you bearer token: ")

headers = {
    "Authorization": f"Bearer {token}"
}

try:
    response = requests.get(url_path, headers=headers)
except Exception as e:
    print(f"Error: {e}")

if response.status_code == 200:
    data = response.json()
else:
    print(response.status_code, response.text)

movies = data["results"]

print("----------------------")
for movie in movies:
    print(movie["title"])
    print(movie["overview"])
    print(f"Avg rating: {movie['vote_average']}")
    print("----------------------")
